version: '3.8'

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: sigpp-db
    restart: always
    environment:
      POSTGRES_DB: sigpp_db
      POSTGRES_USER: sigpp_user
      POSTGRES_PASSWORD: sigpp_pass_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - sigpp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sigpp_user -d sigpp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sigpp-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://sigpp_user:sigpp_pass_2025@db:5432/sigpp_db
      SECRET_KEY: tu-super-secreto-key-2025-sigpp
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sigpp-network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Vue.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sigpp-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - sigpp-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/api/v1
    command: npm run dev -- --host

volumes:
  postgres_data:
    driver: local

networks:
  sigpp-network:
    driver: bridge
